# Generated by Django 5.2.17 on 2026-09-13 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_created_by_expense_paid_at_and_more'),
        ('procurement', '0009_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_expense', to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('UTILITIES', 'Utilities'), ('TRAVEL', 'Travel'), ('MAINTENANCE', 'Maintenance'), ('SALARY', 'Salary'), ('PROCUREMENT', 'Procurement'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
