# Generated by Django 5.2.17 on 2026-09-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
    ]
