# Generated by Django 5.2.17 on 2026-09-23 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CONFIRM', 'Confirm'), ('ORDER', 'Order'), ('RECEIVE', 'Receive'), ('COMPLETE', 'Complete'), ('CANCEL', 'Cancel'), ('PAY', 'Pay'), ('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('ADJUST', 'Adjust')], max_length=30)),
                ('module', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('entity_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='audit_created_idx'), models.Index(fields=['module', 'action'], name='audit_module_action_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_entity_idx')],
            },
        ),
    ]
